# Utiliser une image de base contenant Java
FROM openjdk:17-jdk-slim

# Définir le répertoire de travail à l'intérieur du conteneur
WORKDIR /app

# Copier le fichier JAR généré par Maven ou Gradle vers le conteneur
COPY target/SmartFeedback.jar /app/SmartFeedback.jar

# Exposer le port sur lequel l'application Spring Boot écoute
EXPOSE 8080

# Démarrer l'application Spring Boot avec le fichier JAR
CMD ["java", "-jar", "/app/SmartFeedback.jar"]
